Repository ExtremeFLOW/neko-top, pull requests merged in 2025-03, with the labels that each got.

#103 Refactor the design_t
  examples/rugby_ball/driver.f90
  examples/rugby_verification/driver.f90
  examples/rugby_verification/rugby_ball.case
  sources/CMakeLists.txt
  sources/designs/design.f90
  sources/designs/design_brinkman.f90
  sources/designs/design_factory.f90
  sources/designs/design_simple.f90
  sources/optimizer/mma_optimizer.f90
  sources/problems/constraints/volume_constraint.f90
  sources/problems/objectives/lube_term_objective.f90
  sources/problems/objectives/minimum_dissipation_objective.f90
  sources/source_terms/adjoint_lube_source_term.f90
  sources/topology_optimization/user_module.f90
Labels: enhancement

#125 Sync formatting to neko standards
  .github/workflows/check_formatting.yml
Labels: ci/cd

#122 Ensure cross compilation support and clean up build flags
  CMakeLists.txt
  cmake/build_flags.cmake
Labels: enhancement, compiler

#123 Fix aliasing module references
  examples/rugby_ball/driver.f90
  examples/rugby_verification/driver.f90
  sources/designs/design.f90
  sources/designs/design_brinkman.f90
  sources/designs/design_simple.f90
  sources/optimizer/mma_optimizer.f90
  sources/optimizer/optimizer.f90
  sources/problems/base_functional.f90
  sources/problems/constraint.f90
  sources/problems/constraints/volume_constraint.f90
  sources/problems/objective.f90
  sources/problems/objectives/lube_term_objective.f90
  sources/problems/objectives/minimum_dissipation_objective.f90
  sources/problems/problem.f90
  sources/simulation/simulation.f90
Labels: bug, compiler

#138 Improve documentation and fix formatting issues
  .github/workflows/deploy_documentation.yml
  documentation/Doxyfile.in
  documentation/pages/neko-top.md
  documentation/pages/theory/adjoint.md
  examples/power_iterations/readme.md
  examples/rugby_ball/readme.md
  examples/rugby_verification/README.md
  sources/adjoint/adjoint_fluid_pnpn.f90
  sources/adjoint/adjoint_fluid_scheme.f90
  sources/adjoint/adv_adjoint_dealias.f90
  sources/adjoint/adv_adjoint_no_dealias.f90
  sources/adjoint/advection_adjoint_fctry.f90
  sources/designs/design.f90
  sources/mapping_functions/PDE_filter_mapping.f90
  sources/mapping_functions/RAMP_mapping.f90
  sources/mapping_functions/linear_mapping.f90
  sources/mapping_functions/mapping.f90
  sources/mapping_functions/mapping_handler.f90
  sources/neko_ext/mask_ops.f90
  sources/neko_ext/neko_ext.f90
  sources/optimizer/optimizer.f90
  sources/problems/constraint.f90
  sources/problems/constraints/volume_constraint.f90
  sources/problems/objective.f90
  sources/problems/objectives/lube_term_objective.f90
  sources/problems/objectives/minimum_dissipation_objective.f90
  sources/problems/problem.f90
  sources/source_terms/adjoint_lube_source_term.f90
  sources/source_terms/adjoint_minimum_dissipation_source_term.f90
  sources/source_terms/simple_brinkman_source_term.f90
  sources/topology_optimization/topopt_brinkman_source.f90
Labels: documentation

#139 Optimization domain in JSON
  examples/rugby_ball/rugby_ball.case
  examples/rugby_verification/rugby_ball.case
  sources/designs/design_brinkman.f90
Labels: enhancement, help wanted

#120 Improve build process and device handling
  CMakeLists.txt
  cmake/build_example.cmake
  scripts/dependencies.sh
  setup.sh
  sources/CMakeLists.txt
Labels: bug, compiler, script

#140 Add option to build documentation
  .github/workflows/check_documentation.yml
  .gitignore
  documentation/CMakeLists.txt
  documentation/Doxyfile.in
  setup.sh
Labels: documentation, script
